### ISSUE TITLE
ログイン機能

### ISSUE THREAD

**Issue by penguinwokrs** [aquanote/rails-training#2]
### 前提
gemのdevise-token-authを使って下さい。

### 機能要件
JSONで以下のリクエストを送り以下のレスポンスを返すAPIを実装して下さい。
※数値はsampleです
レスポンスに関しては最低限、書かれている項目を返すようにして下さい。

* ユーザー登録機能
  - (email, password)
* ユーザーログイン

#### リクエスト
`
{
    "user_name": "yamada",
    "email": "yamada@example.com",
    "password": "1234abc",
}
`
#### レスポンス

`
{
    "status": "ok",
    "uid": yamada@example.com",
     "access-token": "ykhzpkQS2WvegSVY0_5JVw",
     "client": "8EU8--vzMaUAloh5Kzl3OQ"
}
`

#### リクエスト
`
{
	"email": "yamada@example.com",
	"password": "1234abc"
}
`

#### レスポンス

`
{
                "uid": yamada@example.com",
		"access-token": "ykhzpkQS2WvegSVY0_5JVw",
		"client": "8EU8--vzMaUAloh5Kzl3OQ"
}
`

**Comment by aquanote** [comment]
@penguinwokrs jsonのキー名にハイフンは使用できますか？"access-token"の出力でハマっています。

**Comment by penguinwokrs** [comment]
@aquanote ハイフンは使用できます。
ブランチをPushして頂ければ、レビューも出来るので、途中でもプルリクエストください。

**Comment by aquanote** [comment]
@penguinwokrs 遅い時間にすみません。。。ちょっと時間考えます。
対象箇所 https://github.com/aquanote/rails-training/pull/7/commits/7ac542ea8833dfe85f616608ebcc8df04065dc9e#diff-3620e29f2e357fb66feba2bdff27095aR3

**Comment by penguinwokrs** [comment]
シリアライズでjbuilderが使いづらければ、ActiveModel::Serializersに切り替えてる選択肢もありますね。
書き直しが必要なのでおまかせします。

**Comment by penguinwokrs** [comment]
シリアライズでjbuilderが使いづらければ、ActiveModel::Serializersに切り替えてる選択肢もありますね。
書き直しが必要なのでおまかせします。

**Comment by penguinwokrs** [comment]
シリアライズでjbuilderが使いづらければ、ActiveModel::Serializers に切り替えてる選択肢もありますね。
書き直しが必要なのでおまかせします。

**Comment by penguinwokrs** [comment]
シリアライズでjbuilderが使いづらければ、ActiveModel::Serializersに切り替えてる選択肢もありますね。
書き直しが必要なのでおまかせします。

**Comment by aquanote** [comment]
@penguinwokrs 質問の仕方悪くすみません。
特にjbuilderが使いづらいわけではなくハイフン付きのキー指定方法がわからない状態だっただけなのですが、リテラル指定で対処しました。
https://github.com/aquanote/rails-training/pull/7/commits/d0d8ca4587dd0e39726f0f4b06b7ee5da93680ac#diff-3620e29f2e357fb66feba2bdff27095aR3

**Comment by aquanote** [comment]
一旦最低限の要件は満たせたのでクローズ致します。
